Plataforma/main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = (
    path("", views.homepage, name="homepage"),
    path("register", views.register, name="register"),
    path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
    path("add_status", views.add_status, name="add_status"),
    path("add_equipment", views.add_equipment, name="add_equipment"),
    path("account", views.dashboard, name='dashboard'),
    path("pivot_data", views.pivot_data, name='pivot_data'),
    path("pivot_data2", views.pivot_data2, name='pivot_data2'),
    path("<single_slug>", views.single_slug_request, name="single_slug"),
)

Plataforma/main/templates/main/add_equipment.html
{% extends "main/header.html" %}

{% block content %}
	<h1><p style="font-size:30px">Adicionar Novo Equipamento</p></h1>

		<form method="POST" enctype="multipart/form-data">

			{% csrf_token %}
			{{form.as_p}}

			<br>

			<button class="btn" type="submit">Adicionar</button>

		</form>

		<br>
<!--	If you don´t already have an account, <a href="/register"><strong>register</strong></a> for one.-->
{% endblock %}

Plataforma/main/templates/main/add_status.html
{% extends "main/header.html" %}

{% block content %}
	<h1><p style="font-size:30px">Adicionar Novo Status</p></h1>

		<hr style="width:100%;text-align:left;margin-left:0">

			<div>
				<p style="font-size:15px">Passos:</p>
				<p style="font-size:10px">1 - Dê um título que resume a atualização.</p>
				<p style="font-size:10px">2 - Selecione a categoria e tipo de equipamento.</p>
				<p style="font-size:10px">3 - Descreva em detalhes o status atual/o que foi realizado.</p>
				<p style="font-size:10px">4 - Adicione uma foto caso seja necessário.</p>
			</div>

		<hr style="width:100%;text-align:left;margin-left:0">

		<form method="POST" enctype="multipart/form-data">

			{% csrf_token %}
			{{form.as_p}}

			<br>

			<button class="btn" type="submit">Adicionar</button>

		</form>

		<br>
<!--	If you don´t already have an account, <a href="/register"><strong>register</strong></a> for one.-->
{% endblock %}

Plataforma/main/templates/main/categories.html
{% extends 'main/header.html' %}

{% block content %}

    <div class="row">
        <p style="font-size:20px">Selecione a categoria desejada:</p>
        {% for cat in categories %}
            <div class="col s12 m6 l4">
                <a href="{{cat.category_slug}}", style="color:#000">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div class="card-title">{{cat.category_name}}</div>
                            <p style="font-size:12px"> {{cat.category_summary}}</p>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}

    </div>
{% endblock %}

Plataforma/main/templates/main/dashboard.html
{% extends "main/header.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        Clique para cobrar equipamentos com mais de uma semana sem atualizações.
        <br>
        <button type="submit" name="run_script">Cobrar Atualizações</button>
    </form>

    <html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard with Flexmonster</title>
    <script src="https://cdn.flexmonster.com/flexmonster.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://cdn.flexmonster.com/demo.css">
    <style>
/* Charts Style  */

.fm-charts-color-1 {
  fill: #ffa600 !important;
}

.fm-charts-color-2 {
  fill: #7eae26 !important;
}

.fm-charts-color-3 {
  fill: #00a45a !important;
}

.fm-charts-color-4 {
  fill: #df3800 !important;
}

.fm-charts-color-5 {
  fill: #e95800 !important;
}

.fm-charts-color-6 {
  fill: #ffa600 !important;
}</style>
</head>
<body>
<div id="pivot-table-container1" data-url="{% url 'main:pivot_data' %}"></div>
<div id="pivot-table-container2" data-url2="{% url 'main:pivot_data2' %}"></div>
<div id="pivot-chart-container1"></div>
<div id="pivot-chart-container2"></div>
<div id="pivot-chart-container3"></div>
<div id="pivot-chart-container4"></div>
<script>
function processData(dataset) {
    var result = []
    dataset = JSON.parse(dataset);
    dataset.forEach(item => result.push(item.fields));
    return result;
}
$.ajax({
    url: $("#pivot-table-container1").attr("data-url"),
    dataType: 'json',
    success: function(data) {
        new Flexmonster({
            container: "#pivot-chart-container1",
            componentFolder: "https://cdn.flexmonster.com/",
            width: "100%",
            height: 400,
            //toolbar: true,
            report: {
                dataSource: {
                    type: "json",
                    data: processData(data)
                },
                slice: {
                    "rows": [{
                        "uniqueName": "equipment_status"
                    }],
                    "measures": [{
                            "uniqueName": "equipment_status",
                            "aggregation": "% of Grand Total"
                        },
                    ]
                },
                "options": {
                    "viewType": "charts",
                    "chart": {
                        "type": "pie"
                    }
                }
            }
        });
        new Flexmonster({
            container: "#pivot-chart-container2",
            componentFolder: "https://cdn.flexmonster.com/",
            width: "100%",
            height: 500,
            //toolbar: true,
            report: {
                dataSource: {
                    type: "json",
                    data: processData(data)
                },
                slice: {
                    "rows": [{
                        "uniqueName": "equipment_company"
                    }],
                    "measures": [{
                            "uniqueName": "equipment_company",
                            "aggregation": "count"
                        },
                    ]
                },
                "options": {
                    "viewType": "charts",
                    "chart": {
                        "type": "Bar"
                    }
                }
            }
        });
    }
});
$.ajax({
    url: $("#pivot-table-container2").attr("data-url2"),
    dataType: 'json',
    success: function(data) {
        new Flexmonster({
            container: "#pivot-chart-container3",
            componentFolder: "https://cdn.flexmonster.com/",
            width: "100%",
            height: 500,
            //toolbar: true,
            report: {
                dataSource: {
                    type: "json",
                    data: processData(data)
                },
                slice: {
                    "rows": [{
                        "uniqueName": "status_published.Month"
                    }],
                    "measures": [{
                            "uniqueName": "status_published.Month",
                            "aggregation": "Count"
                        },
                    ]
                },
                "options": {
                    "viewType": "charts",
                    "chart": {
                        "type": "Column"
                    }
                }
            }
        });
    }
});
</script>
</body>
</html>
{% endblock %}

Plataforma/main/templates/main/equipment.html
{% extends 'main/header.html' %}

{% block content %}

{% if user.is_authenticated %}
    <div class="row">
        <p style="font-size:20px">Selecione o equipamento desejado:</p>
            {% if equipments %}
                {% for item in equipments %}
                    {% if username == item.equipment_user_username or user.is_superuser %}
                        <div class="col-lg-4 d-flex align-items-stretch">
                            <a href="{{item.equipment_slug}}" style="color:#000">
                                <div class="card hoverable">
                                    <div class="card-content">
                                        <div class="card-title" style="font-size:18px">{{item.equipment_name}}</div>
                                        <p>ID: {{item.equipment_id}}</p>
                                        <p>{{item.equipment_summary}}</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                <p style="font-size:14px">Não há equipamentos cadastrados para sua empresa. Abra uma solicitação.</p>
            {% endif %}
    </div>
{% else %}
        <p style="font-size:18px">Usuário não logado. Faça o login para acessar seus dados.</p>
{% endif %}

{% endblock %}

Plataforma/main/templates/main/header.html
<head>
	{% load static %}
	<link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">
	<!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified Jquery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
    $(document).ready(function(){
        $('select').formSelect();
    });
    </script>
</head>


<body>
	
  {% include "main/includes/navbar.html" %}

  {% include "main/includes/messages.html" %}

  <div class="container">
	<br>
	{% block content %}
	{% endblock %}
  </div>
  
</body>

<script src="{% static 'tinymce/js/prism.js' %}"></script>

Plataforma/main/templates/main/home.html
{% extends "main/header.html" %}

{% block content %}
  <div class="row">
	 {% for tut in tutorials %}
		<div class="col s12 m8 l6">
		  <div class="card blue-grey darken-1">
			<div class="card-content white-text">
			  <span class="card-title">{{tut.tutorial_title}}</span>
			  <p style="font-size:70%">{{tut.tutorial_published}}</p>
			  <p>{{tut.tutorial_content|safe}}</p>
			</div>
			<div class="card-action">
			  <a href="#">Visit</a>
			</div>
		  </div>
		</div>
    {% endfor %}
  </div>
{% endblock %}	

Plataforma/main/templates/main/login.html
{% extends "main/header.html" %}

{% block content %}
	<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		
		<button class="btn" type="submit">login</button>
	</form>
	
	If you don´t already have an account, <a href="/register"><strong>register</strong></a> for one.
{% endblock %}	

Plataforma/main/templates/main/register.html
{% extends "main/header.html" %}

{% block content %}
	<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		{{profile_form.as_p}}
		
		<button class="btn" type="submit">register</button>
	</form>
	
	If you already have an account, <a href="/login"><strong>login</strong></a> instead.
{% endblock %}	

Plataforma/main/templates/main/status.html
{% extends 'main/header.html' %}

{% block content %}

    {% if user.is_authenticated %}
                <div class="row">
                    <p style="font-size:20px">Status geral do equipamento:</p>
                    <div class="row">
                        {% if equipment %}
                            {% for item in equipment %}
                                <div class="col s10 m10 l10">
                                        <div class="card hoverable orange darken-0">
                                            <div class="card-content">
                                                <div class="card-title"><b>{{item.equipment_name}}</b></div>
                                                <p><b>ID:</b> {{item.equipment_id}}</p>
                                                <p><b>Descrição:</b> {{item.equipment_summary}}</p>
                                                <p><b>Status atual:</b> {{item.equipment_status}}</p>
                                                <p><b>Data de início:</b> {{item.equipment_published}}</p>
                                                <p><b>Empresa Terceira:</b> {{item.equipment_company}}</p>
                                            </div>
                                        </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <p style="font-size:14px">Nehnum equipamento cadastrado.</p>
                        {% endif %}
                    </div>
                    <p style="font-size:20px">Etapas e atualizações realizadas:</p>
                    {% if status_ %}
                        {% for item2 in status_ %}
                            <div class="col s10 m10 l10">
                                <div class="card hoverable">
                                    <div class="card-content">
                                        <div class="card-title">{{item2.status_title}}</div>
                                        <p style="font-size:70%">Publicado {{item2.status_published}}</p>
                                        <hr style="width:100%;text-align:left;margin-left:0">
                                        {{item2.status_content|safe}}
                                        {% if item2.status_image.url != null %}
                                            <hr style="width:100%;text-align:left;margin-left:0">
                                            <p class="post_image"><img src="{{ item2.status_image.url }}" alt="" width="100%"></p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% else %}
                        <p style="font-size:14px">Sem atualizações disponíveis.</p>
                    {% endif %}
                </div>
    {% else %}
        <p style="font-size:18px">Usuário não logado. Faça o login para acessar seus dados.</p>
    {% endif %}

{% endblock %}